import { z } from 'zod';

export const patientRegistrationSchema = z.object({
  fullName: z.string().min(2, "Full name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  // Password is auto-generated by the server action if omitted
  password: z.string().optional(), 
  
  // Replaced Age with Date of Birth
  dateOfBirth: z.string().min(1, "Date of birth is required"),
  gender: z.string().min(1, "Please select a gender"),
  phoneNumber: z.string().min(10, "Phone number must be at least 10 digits"),
  
  // Removed painSeverity
  oaDiagnosis: z.enum(["Yes", "No"]),
  affectedKnee: z.string().optional(),
  occupation: z.string().optional(),
  activityLevel: z.string().min(1, "Please select an activity level"),
  deviceMac: z.string().max(17).optional().or(z.literal('')),

  // Added Biomechanical & Emergency Data
  heightCm: z.coerce.number().min(50).max(300).optional().or(z.literal('')),
  weightKg: z.coerce.number().min(20).max(400).optional().or(z.literal('')),
  emergencyContactName: z.string().optional(),
  emergencyContactPhone: z.string().optional(),
});